name: 'Card Moved Notifier'
description: 'Notifies the issue assignee when its corresponding project card is moved between columns.'
inputs:
  token:
    description: 'The GitHub authentication token.'
    required: false
    default: ${{ github.token }}
  assigneeFilter:
    description: 'Only send notifications for the specified assignees. Use comma seperated values.'
    default: ''
runs:
  using: 'node12'
  main: 'index.js'
